amphibians_worldwide/urls.py
from os import stat
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('home/', include('home.urls')),
    path('home/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from . import views

app_name = 'home'
urlpatterns = [
   
    path('', views.index_view, name='index'),
    path('iNaturalist', RedirectView.as_view(url='https://www.inaturalist.org/'), name = 'iNaturalist'),
    path('search/data_summary', views.data_summary_view, name='data_summary'),
    path('search/taxonomy', views.taxonomy_view, name='taxonomy'),
    path('search/tax_order', views.tax_order_view, name = 'tax_order'),
    path('search/tax_family', views.tax_family_view, name = 'tax_family'),
    path('search/tax_genus', views.tax_genus_view, name = 'tax_genus'),
    path('search/location', views.location_view, name='location'),
    path('search/loca_continent', views.loca_continent_view, name='loca_continent'),
    path('search/loca_country', views.loca_country_view, name='loca_country'),
    path('search/micro_habitat', views.micro_habitat_view, name='micro_habitat'),
    path('search/activity', views.activity_view, name='activity'),
    path('search/population_trend', views.population_trend_view, name='population_trend'),
    path('search/iucn', views.iucn_view, name='iucn'),
    path('search/nesting_site', views.nesting_site_view, name='nesting_site'),
    path('search/parity_mode', views.parity_mode_view, name='parity_mode'),
    path('search/species', views.Species_List_View.as_view(), name = 'species'),
    path('search/species/<int:pk>/', views.Species_Detail_Detail_View.as_view(), name = 'species_detail'),
    path('search/search_species/', views.search_species_latin_name_view, name = 'search_species_latin'),
    # path('search/search_species/', views.search_species_name_common_view, name = 'search_species_common'),
    path('search/species/parity_mode/<int:parity_mode_id>/', views.Species_Parity_List_View.as_view(), name='species_parity_mode'),
    path('search/species/pop_trend/<int:pop_trend_id>/', views.Species_Pop_Trend_List_View.as_view(), name='species_pop_trend'),
    path('search/species/iucn/<int:iucn_id>/', views.Species_Iucn_List_View.as_view(), name='species_iucn'),
    path('search/species/nesting_site/<int:nesting_site_id>/', views.Species_Nesting_List_View.as_view(), name='species_nesting_site'),
    path('search/species/micro_habitat/<int:micro_habitat_id>/', views.Species_Micro_Habitat_List_View.as_view(), name='species_micro_habitat'),
    path('search/species/activity/<int:activity_id>/', views.Species_Activity_List_View.as_view(), name='species_activity'),
    path('search/species/country/<int:country_id>/', views.Species_Country_List_View.as_view(), name='species_country'),
    path('search/species/continent/<int:continent_id>/', views.Species_Continent_List_View.as_view(), name='species_continent'),
    path('search/species/order/<int:order_id>/', views.Species_Tax_Order_List_View.as_view(), name='species_order'),
    path('search/species/family/<int:family_id>/', views.Species_Family_List_View.as_view(), name='species_family'),
    path('search/species/genus/<int:genus_id>/', views.Species_Genus_List_View.as_view(), name='species_genus'),
    path('account/mypage/', views.my_page_view, name = 'mypage'),
    path('account/profile_page/<int:pk>', views.User_Profile_Detail_View.as_view(), name = 'profile_page'),
    path('account/update_account/', views.update_account_view, name = 'update_account'),
    path('account/my_submissions/<int:user>', views.My_Submissions_List_View.as_view(), name = 'my_submissions'),
    path('account/submit_species/', views.submit_species_view, name = 'submit_species'),
    path('staff/edit_species/<int:species_id>', views.edit_species_view, name = 'edit_species'),
    path('staff/approve_species/<int:pk>', views.Approve_Species_Update_View.as_view(), name = 'approve_species'),
    path('staff/delete_species/<int:pk>', views.Delete_Species_Delete_View.as_view(), name = 'delete_species'),
    path('staff/species/unverified/', views.Species_Unverified_List_View.as_view(), name='species_unverified'),
    path('signup', views.signup_view, name = 'signup'),
    path('login_user', views.login_user_view, name = 'login'),
    path('logout_user', views.logout_user_view, name = 'logout'),
    path('staff/species_pdf_creator/<int:pk>', views.species_render_pdf_view, name='species_pdf_creator'),

    

    
]

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView, ListView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse_lazy
from django.db.models import Count

from home.forms import *
from .models import *

#xhtml2pdf imports
import os
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders



#Index View
def index_view(request):
    return render(request, 'home/index.html', {})

#Data Summary View
def data_summary_view(request):
    #Taxonomy Breakdown
    num_genus = Genus.objects.all().count()
    num_species = Species.objects.all().count()
    num_families = Family.objects.all().count()
    num_orders = Order_Taxon.objects.all().count()

    #Variable Breakdown
    #Many to Many
    activity_ranking = Activity.objects.all().annotate(count=Count('activity_id')).order_by("-count")
    nesting_site_ranking = Nesting_Site.objects.all().annotate(count=Count('nesting_site_id')).order_by("-count")
    microhabitat_ranking = Micro_Habitat.objects.all().annotate(count=Count('micro_habitat_id')).order_by("-count")

    #One to Many
    parity_mode_ranking = Parity_Mode.objects.all().annotate(count=Count('parity_mode_id')).order_by('-count')
    pop_trend_ranking = Pop_Trend.objects.all().annotate(count=Count('pop_trend_id')).order_by("-count")
    iucn_ranking = IUCN.objects.all().annotate(count=Count('iucn_id')).order_by("-count")
    

    #Geographical Representations 
    continent_ranking = Continent.objects.all().annotate(count=Count('continent_id')).order_by('-count')
    country_ranking = Country.objects.all().annotate(count=Count('country_id')).order_by('-count')

    context = {
        'num_genus':  num_genus,
        'num_species': num_species,
        'num_families': num_families,
        'num_orders': num_orders,
        'activity_ranking': activity_ranking,
        'nesting_site_ranking':  nesting_site_ranking,
        'microhabitat_ranking': microhabitat_ranking,
        'parity_mode_ranking': parity_mode_ranking,
        'pop_trend_ranking': pop_trend_ranking,
        'iucn_ranking': iucn_ranking,
        'continent_ranking': continent_ranking,
        'country_ranking':country_ranking,
      
    
    }
    return render(request, 'home/search/data_summary.html', context)

###################################################PDF Generator#########################################################
def species_render_pdf_view(request, *args, **kwargs):
    pk = kwargs.get('pk')
    species = get_object_or_404(Species, pk=pk)

    template_path = 'home/staff/pdf_creator.html'
    context = {'species': species}
    # Creates a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="species.pdf"'
    # finds the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # creates a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response



#################################################Nav Bar Views#######################################################

def location_view(request):
    return render(request, 'home/search/location.html')

def loca_continent_view(request):
    continent_list = Continent.objects.all().order_by('continent_name')
    return render (request, 'home/search/loca_continent.html', {'continent_list': continent_list})

def loca_country_view(request):
    country_list = Country.objects.all().order_by('country_name')
    return render (request, 'home/search/loca_country.html', {'country_list': country_list})

def micro_habitat_view(request):
    micro_habitat_list = Micro_Habitat.objects.all().order_by('micro_habitat_name')
    return render(request, 'home/search/micro_habitat.html', {'micro_habitat_list': micro_habitat_list})

def activity_view(request):
    activity_list = Activity.objects.all().order_by('activity_kind')
    return render(request, 'home/search/activity.html', {'activity_list': activity_list})

def population_trend_view(request):
    pop_trend_list = Pop_Trend.objects.all().order_by('pop_trend_status')
    return render(request, 'home/search/population_trend.html', {'pop_trend_list': pop_trend_list})

def iucn_view(request):
     iucn_list = IUCN.objects.all().order_by('iucn_status')
     return render(request, 'home/search/iucn.html', {'iucn_list': iucn_list})

def nesting_site_view(request):
    nesting_site_list = Nesting_Site.objects.all().order_by('nesting_site_desc')
    return render(request, 'home/search/nesting_site.html', {'nesting_site_list': nesting_site_list})

def parity_mode_view(request):
    parity_mode_list = Parity_Mode.objects.all().order_by('parity_mode_desc')
    return render(request, 'home/search/parity_mode.html', {'parity_mode_list': parity_mode_list})

def taxonomy_view(request):
    return render(request, 'home/search/taxonomy.html')

def tax_order_view(request):
    order_taxon_list = Order_Taxon.objects.all().order_by('order_taxon_name')
    return render(request, 'home/search/tax_order.html', {'order_taxon_list': order_taxon_list})


def tax_family_view(request):
    family_list = Family.objects.all().order_by('family_name')
    return render(request, 'home/search/tax_family.html', {'family_list': family_list})


def tax_genus_view(request):
    genus_list = Genus.objects.all().order_by('genus_name')
    return render(request, 'home/search/tax_genus.html', {'genus_list': genus_list})


###############################################Search Views########################################################
  
def search_species_latin_name_view(request):

    if request.method == "POST":
        searched= request.POST['searched']
        species_results = Species.objects.filter(species_name_latin__contains = searched).order_by('species_name_latin' )
        
        return render(request, 'home/search/search_species.html', {'searched':searched, 'species_results':species_results})

    else:
        
        return redirect ('home:index')

    
###############################################Species Views######################################################

class Species_List_View(ListView):
    paginate_by = 20
    model = Species
    template_name = "home/search/species.html"
    context_object_name = 'species_list'

class Species_Detail_Detail_View (DetailView):
    model = Species
    template_name = "home/search/species_detail.html"
    context_object_name = 'species_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order_list'] = Order_Taxon.objects.filter(family__genus__genus_id=context['object'].genus_id)
        context['family_list'] = Family.objects.filter(genus__genus_id=context['object'].genus_id)
        context['country_list'] = Country.objects.filter(geo_location__geo_location_species__species_id=context['object'].species_id)
        context['continent_list'] = Continent.objects.filter(country__geo_location__geo_location_species__species_id=context['object'].species_id)

        return context
   

###########################################One to Many Views########################################################

class Species_Parity_List_View(ListView):
    paginate_by = 20
    model = Species
    template_name = "home/search/species.html"
    context_object_name = 'species_list'
    

    def get_queryset(self):
    
        return Species.objects.filter(parity_mode_id=self.kwargs['parity_mode_id']).order_by('species_name_latin')



class Species_Pop_Trend_List_View(ListView):
    paginate_by = 20
    model = Species
    template_name = "home/search/species.html"
    context_object_name = 'species_list'

    def get_queryset(self):
    
        return Species.objects.filter(pop_trend_id=self.kwargs['pop_trend_id']).order_by('species_name_latin')


class Species_Iucn_List_View(ListView):
    paginate_by = 20
    model = Species
    template_name = "home/search/species.html"
    context_object_name = 'species_list'


    def get_queryset(self):
    
        return Species.objects.filter(iucn_id=self.kwargs['iucn_id']).order_by('species_name_latin')



################################################Many to Many Views###################################################

class Species_Nesting_List_View(ListView):
    paginate_by = 20
    model = Species
    template_name = "home/search/species.html"
    context_object_name = 'species_list'
    
    def get_queryset(self): 

        return Species.objects.filter(nesting_site_species__nesting_site__nesting_site_id= self.kwargs['nesting_site_id']).order_by('species_name_latin')

    

class Species_Micro_Habitat_List_View(ListView):
    paginate_by = 20
    model = Species
    template_name = "home/search/species.html"
    context_object_name = 'species_list'

    def get_queryset(self): 

        return Species.objects.filter(micro_habitat_species__micro_habitat__micro_habitat_id= self.kwargs['micro_habitat_id']).order_by('species_name_latin')



class Species_Activity_List_View(ListView):
    paginate_by = 20
    model = Species
    template_name = "home/search/species.html"
    context_object_name = 'species_list'


    def get_queryset(self): 
        return Species.objects.filter(activity_species__activity__activity_id= self.kwargs['activity_id']).order_by('species_name_latin').order_by('species_name_latin' )
       

###############################################Hierarchical Views####################################################

class Species_Country_List_View(ListView):

home/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  <link rel="stylesheet" href="/static/home/css/myui.css">
  <script src="https://kit.fontawesome.com/ef76ad224f.js" crossorigin="anonymous"></script>
  <title>{% block title %} Amphibians Worldwide {% endblock %}</title>
</head>

<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">

      <a class="button is-info has-text-success" href="{% url 'home:index' %}"> <span class="icon-text">
          <span class="icon">
            <i class="fa-solid fa-frog"></i>
          </span>
          <span>Amphibians Worldwide</span>
          <span class="icon">
            <i class="fa-solid fa-earth-europe"></i>
          </span>
        </span>
      </a>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
  </div>

  <div class="navbar-end">
    <div class="navbar-item">
      <div class="buttons">
        {% if user.is_authenticated %}
        <div class="dropdown is-hoverable">
          <div class="dropdown-trigger">
            <button class="button is-success has-text-info" aria-haspopup="true" aria-controls="dropdown-menu">
              <span>Account</span>
              <span class="icon is-small">
                <i class="fas fa-angle-down" aria-hidden="true"></i>
              </span>
            </button>
          </div>
          <div class="dropdown-menu" id="dropdown-menu" role="menu">
            <div class="dropdown-content">
              <a href="{% url 'home:mypage'  %}" class="dropdown-item">
                <strong>My Page</strong>
              </a>
              <a href="{% url 'home:my_submissions' user=user.pk %}" class="dropdown-item">
                <strong>My Submissions</strong>
              </a>
              <a href="{% url 'home:update_account' %}" class="dropdown-item">
                <strong>Update Account</strong>
              </a>
              <a href="{% url 'home:submit_species' %}" class="dropdown-item">
                <strong>Submit Species</strong>
              </a>

              {% if user.is_staff %}
              <a href="{% url 'home:species_unverified' %}" class="dropdown-item">
                <strong>Unverified Species</strong>
              </a>
              {% endif %}

            </div>
          </div>
        </div>



        <a class="button is-info has-text-success" href="{% url 'home:logout' %}">
          Logout
        </a>
        {% else %}
        <a class="button is-success has-text-info" href="{% url 'home:signup' %}">
          Sign Up
        </a>
        <a class="button is-info has-text-success" href="{% url 'home:login' %}">
          Login
        </a>
        {% endif %}



      </div>
    </div>
  </div>
  </div>
</nav>


<body>
  <!-- <script src="/static/home/js/tablesort.js"> </script> -->
  {% block content %}

  {% endblock %}
</body>


<footer class="footer px-5 py-1">
  <div class="navbar-item">
    <div class="buttons">
      <a class="button is-success has-text-info" href="mailto: eeecs@qubsupport.com">
        Help
      </a>

      <a class="button is-info has-text-success" href="{% url 'home:iNaturalist' %}">
        iNaturalist
      </a>
    </div>
  </div>



</footer>

</html>