amphibians_worldwide/urls.py
from os import stat
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('home/', include('home.urls')),
    path('home/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from . import views

app_name = 'home'
urlpatterns = [
   
    path('', views.index_view, name='index'),
    path('iNaturalist', RedirectView.as_view(url='https://www.inaturalist.org/'), name = 'iNaturalist'),
    path('search/data_summary', views.data_summary_view, name='data_summary'),
    path('search/taxonomy', views.taxonomy_view, name='taxonomy'),
    path('search/tax_order', views.tax_order_view, name = 'tax_order'),
    path('search/tax_family', views.tax_family_view, name = 'tax_family'),
    path('search/tax_genus', views.tax_genus_view, name = 'tax_genus'),
    path('search/location', views.location_view, name='location'),
    path('search/loca_continent', views.loca_continent_view, name='loca_continent'),
    path('search/loca_country', views.loca_country_view, name='loca_country'),
    path('search/micro_habitat', views.micro_habitat_view, name='micro_habitat'),
    path('search/activity', views.activity_view, name='activity'),
    path('search/population_trend', views.population_trend_view, name='population_trend'),
    path('search/iucn', views.iucn_view, name='iucn'),
    path('search/nesting_site', views.nesting_site_view, name='nesting_site'),
    path('search/parity_mode', views.parity_mode_view, name='parity_mode'),
    path('search/species', views.Species_List_View.as_view(), name = 'species'),
    path('search/species/<int:pk>/', views.Species_Detail_Detail_View.as_view(), name = 'species_detail'),
    path('search/search_species/', views.search_species_latin_name_view, name = 'search_species_latin'),
    # path('search/search_species/', views.search_species_name_common_view, name = 'search_species_common'),
    path('search/species/parity_mode/<int:parity_mode_id>/', views.Species_Parity_List_View.as_view(), name='species_parity_mode'),
    path('search/species/pop_trend/<int:pop_trend_id>/', views.Species_Pop_Trend_List_View.as_view(), name='species_pop_trend'),
    path('search/species/iucn/<int:iucn_id>/', views.Species_Iucn_List_View.as_view(), name='species_iucn'),
    path('search/species/nesting_site/<int:nesting_site_id>/', views.Species_Nesting_List_View.as_view(), name='species_nesting_site'),
    path('search/species/micro_habitat/<int:micro_habitat_id>/', views.Species_Micro_Habitat_List_View.as_view(), name='species_micro_habitat'),
    path('search/species/activity/<int:activity_id>/', views.Species_Activity_List_View.as_view(), name='species_activity'),
    path('search/species/country/<int:country_id>/', views.Species_Country_List_View.as_view(), name='species_country'),
    path('search/species/continent/<int:continent_id>/', views.Species_Continent_List_View.as_view(), name='species_continent'),
    path('search/species/order/<int:order_id>/', views.Species_Tax_Order_List_View.as_view(), name='species_order'),
    path('search/species/family/<int:family_id>/', views.Species_Family_List_View.as_view(), name='species_family'),
    path('search/species/genus/<int:genus_id>/', views.Species_Genus_List_View.as_view(), name='species_genus'),
    path('account/mypage/', views.my_page_view, name = 'mypage'),
    path('account/profile_page/<int:pk>', views.User_Profile_Detail_View.as_view(), name = 'profile_page'),
    path('account/update_account/', views.update_account_view, name = 'update_account'),
    path('account/my_submissions/<int:user>', views.My_Submissions_List_View.as_view(), name = 'my_submissions'),
    path('account/submit_species/', views.submit_species_view, name = 'submit_species'),
    path('staff/edit_species/<int:species_id>', views.edit_species_view, name = 'edit_species'),
    path('staff/approve_species/<int:pk>', views.Approve_Species_Update_View.as_view(), name = 'approve_species'),
    path('staff/delete_species/<int:pk>', views.Delete_Species_Delete_View.as_view(), name = 'delete_species'),
    path('staff/species/unverified/', views.Species_Unverified_List_View.as_view(), name='species_unverified'),
    path('signup', views.signup_view, name = 'signup'),
    path('login_user', views.login_user_view, name = 'login'),
    path('logout_user', views.logout_user_view, name = 'logout'),
    path('staff/species_pdf_creator/<int:pk>', views.species_render_pdf_view, name='species_pdf_creator'),

    

    
]

home/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.


from django.db import models
from django.contrib.auth.admin import User
from django.urls import reverse
from django.core.exceptions import ValidationError


#Validator to ensure correct data value range is input
def validate_negative(value):
    if value < 0:
        raise ValidationError( ('%(value) is a negative number'), params={'value': value},)

#users
class User_Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    educational_institution = models.CharField(max_length=200, null=True, blank=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to="images/")
    bio = models.TextField(blank=True, null = True)
    university_profile = models.CharField(max_length=200, null=True, blank=True)
    linked_in = models.CharField(max_length=200, null=True, blank=True)
    academia_publication = models.CharField(max_length=200, null=True, blank=True)
    publication_1 = models.CharField(max_length=200, null=True, blank=True)
    publication_2 = models.CharField(max_length=200, null=True, blank=True)
    publication_3 = models.CharField(max_length=200, null=True, blank=True)
    publication_4 = models.CharField(max_length=200, null=True, blank=True)
    publication_5 = models.CharField(max_length=200, null=True, blank=True)
    permission_to_display_contact_information = models.BooleanField(default = False, blank=False, null=False)
    permission_to_display_publications = models.BooleanField(default = False, blank=False, null=False)


    def __str__(self):
        return self.user.username

#One to Many
class Parity_Mode(models.Model):
    parity_mode_id = models.AutoField(primary_key=True)
    parity_mode_desc = models.CharField(max_length=200)

    def __str__(self) :
        return self.parity_mode_desc

    class Meta:
        managed = False
        db_table = 'parity_mode'

class Pop_Trend(models.Model):
    pop_trend_id = models.AutoField(primary_key=True)
    pop_trend_status = models.CharField(max_length=200)

    def __str__(self) :
        return self.pop_trend_status

    class Meta:
        managed = False
        db_table = 'pop_trend'

class IUCN(models.Model):
    iucn_id = models.AutoField(primary_key=True)
    iucn_status = models.CharField(max_length=200)

    def __str__(self) :
        return self.iucn_status

    class Meta:
        managed = False
        db_table = 'iucn'

#Taxonomy Structure
class Order_Taxon(models.Model):
    order_id = models.AutoField(primary_key=True)
    order_taxon_name = models.CharField(max_length=200)

    def __str__(self) :
        return self.order_taxon_name

    class Meta:
        managed = False
        db_table = 'order_taxon'

class Family(models.Model):
    family_id = models.AutoField(primary_key=True)
    family_name = models.CharField(max_length=200)
    order = models.ForeignKey(Order_Taxon, on_delete=models.CASCADE)

    def __str__(self) :
        return self.family_name

    class Meta:
        managed = False
        db_table = 'family'

class Genus(models.Model):
    genus_id = models.AutoField(primary_key=True)
    genus_name = models.CharField(max_length=200)
    family = models.ForeignKey(Family, on_delete=models.CASCADE)
    def __str__(self) :
        return self.genus_name

    class Meta:
        managed = False
        db_table = 'genus'

# Species Structure
class Species(models.Model):
    species_id = models.AutoField(primary_key=True)
    species_name_common = models.CharField(max_length=200, blank=True, null=True)
    species_name_latin = models.CharField(max_length=200, blank=True, null=True)
    size_max_male = models.FloatField(blank=True, null=True, validators=[validate_negative])
    size_max_female = models.FloatField(blank=True, null=True, validators=[validate_negative])
    size_max_record = models.FloatField(blank=True, null=True, validators=[validate_negative])
    longevity = models.FloatField(blank=True, null=True, validators=[validate_negative])
    clutch_min = models.IntegerField(blank=True, null=True, validators=[validate_negative])
    clutch_max = models.IntegerField(blank=True, null=True, validators=[validate_negative])
    clutch_avg = models.FloatField(blank=True, null=True, validators=[validate_negative])
    egg_diameter = models.FloatField(blank=True, null=True, validators=[validate_negative])
    range_size = models.FloatField(blank=True, null=True, validators=[validate_negative])
    elevation_min = models.IntegerField(blank=True, null=True)
    elevation_max = models.FloatField(blank=True, null=True)
    elevation_avg = models.FloatField(blank=True, null=True)
    img_uri_male = models.ImageField(null=True, blank=True, upload_to="images/")
    img_uri_female = models.ImageField(null=True, blank=True, upload_to="images/")
    verif_status = models.BooleanField(default = True, blank=False, null=False)
    

#Foreign Keys for Species Model
    parity_mode = models.ForeignKey(Parity_Mode, on_delete=models.DO_NOTHING, blank=True, null=True)
    pop_trend = models.ForeignKey(Pop_Trend, on_delete=models.DO_NOTHING, blank=True, null=True)
    iucn = models.ForeignKey(IUCN, on_delete=models.DO_NOTHING, blank=True, null=True)
    genus = models.ForeignKey(Genus, on_delete=models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(User,  default='3', on_delete=models.DO_NOTHING)

    def __str__(self) :
        return self.species_name_latin

    @property
    def find_ssd (self):
        return self.size_max_male-self.size_max_female

    def get_absolute_url(self):
        return reverse('home:species_detail', args=(self.species_id,))
        
    class Meta:
        managed = True
        db_table = 'species'

#Geographic Location Structure
class Continent(models.Model):
    continent_id = models.AutoField(primary_key=True)
    continent_name = models.CharField(max_length=200)

    def __str__(self) :
        return self.continent_name

    class Meta:
        managed = False
        db_table = 'continent'

class Country(models.Model):
    country_id = models.AutoField(primary_key=True)
    country_name = models.CharField(max_length=200)
    continent = models.ForeignKey(Continent, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self) :
        return self.country_name

    class Meta:
        managed = False
        db_table = 'country'

class Geo_Location(models.Model):
    geo_location_id = models.AutoField(primary_key=True)
    region_name = models.CharField(max_length=200, null=True, blank=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, blank=True, null=True)
    species_locations = models.ManyToManyField(Species, through='Geo_Location_Species', through_fields=('geo_location', 'species'))

    def __str__(self) :
        return self.region_name

    class Meta:
        managed = False
        db_table = 'geo_location'

class Geo_Location_Species(models.Model):
    geo_location_species_id = models.AutoField(primary_key=True)
    geo_location = models.ForeignKey(Geo_Location, on_delete=models.CASCADE, blank=True, null=True)
    species = models.ForeignKey(Species, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'geo_location_species'

#Many to Many
class Nesting_Site(models.Model):
    nesting_site_id = models.AutoField(primary_key=True)
    nesting_site_desc = models.CharField(max_length=200)
    species_sites = models.ManyToManyField(Species, through='Nesting_Site_Species', through_fields=('nesting_site', 'species'))

    def __str__(self) :
        return self.nesting_site_desc

    class Meta:
        managed = False
        db_table = 'nesting_site' 
        
class Nesting_Site_Species(models.Model):
    nesting_site_species_id = models.AutoField(primary_key=True)
    species = models.ForeignKey(Species, on_delete=models.CASCADE)
    nesting_site = models.ForeignKey(Nesting_Site, on_delete=models.CASCADE)
    def __int__(self) :
        return self.species + self.nesting_site
        
    class Meta:
        managed = False
        db_table = 'nesting_site_species'

class Activity(models.Model):
    activity_id = models.AutoField(primary_key=True)
    activity_kind = models.CharField(max_length=200)
    species_activities = models.ManyToManyField(Species, through='Activity_Species', through_fields=('activity', 'species'))

    def __str__(self) :
        return self.activity_kind

    class Meta:
        managed = False
        db_table = 'activity'

class Activity_Species(models.Model):
    activity_species_id = models.AutoField(primary_key=True)
    species = models.ForeignKey(Species, on_delete=models.CASCADE)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'activity_species'

class Micro_Habitat(models.Model):
    micro_habitat_id = models.AutoField(primary_key=True)
    micro_habitat_name = models.CharField(max_length=200)
    species_micro_habitats = models.ManyToManyField(Species, through='Micro_Habitat_Species', through_fields=('micro_habitat', 'species'))

    def __str__(self) :
        return self.micro_habitat_name

    class Meta:
        managed = False
        db_table = 'micro_habitat'

class Micro_Habitat_Species(models.Model):
    micro_habitat_species_id = models.AutoField(primary_key=True)

home/templates/home/account/my_submissions.html
{% extends 'base.html' %}
{% load static %}
{% block title %} My Submissions {% endblock %}
{% block content %}

<article class="panel is-success">
  <p class="panel-heading">
  </p>
</article>

<nav class="breadcrumb is-centered" aria-label="breadcrumbs">
  <ul>
    <li><a href="{% url 'home:index' %}"><span class="icon is-small">
          <i class="fa-solid fa-frog"></i>
        </span>
        <span><strong>Amphibians Worldwide</strong></span>
        <span class="icon is-small">
          <i class="fa-solid fa-earth-europe"></i>
        </span></a></li>

    <li><a href="javascript:history.back()" aria-current="page"><span class="icon is-small">
          <i class="fa-solid fa-magnifying-glass"></i>
        </span>
        <span><strong>Filtered By</strong>
        </span></a></li>

    <li class="is-active"><a href="#" aria-current="page"><span class="icon is-small">
          <i class="fa-solid fa-frog"></i>
        </span>
        <span><strong>My Submissions</strong>
        </span>
        <span class="icon is-small">
          <i class="fa-solid fa-book"></i>
        </span>

      </a></li>

  </ul>
</nav>



<section class="section">
  <div class="container">
    <div class="columns is-multiline  is-mobile">

      {% for species in species_list %}

      <div class="column is-one-third">
        <div class="card csscard  has-background-light">
          <div class="content cardcontent">
            <p class="title is-4">{{ species.genus.genus_name }} {{ species.species_name_latin }}</p>
          </div>
          <div class="card-image csscardimage">
            <p class="subtitle is-6"> Male </p>
            {% if species.img_uri_male%}
            <figure class="is-align-items-center is-justify-content-center image is-3by2">
              <img src="{{ species.img_uri_male.url }}">
            </figure>
            {% else %}
            <figure class="is-align-items-center is-justify-content-center image is-3by2">
              <img src="{% static 'home/images/male_frog.jpg' %}">
            </figure>
            {% endif %}


            <p class="subtitle is-6"> Female </p>
            {% if species.img_uri_female%}
            <figure class="is-align-items-center is-justify-content-center image is-3by2">
              <img src="{{ species.img_uri_female.url}}" </figure>
              {% else %}
              <figure class="is-align-items-center is-justify-content-center image is-3by2">
                <img src="{% static 'home/images/female_frog.jpg' %}">
              </figure>
              {% endif %}
          </div>
          <div class="content cardcontent">

            <p class="subtitle is-6"><strong>Submitted by: </strong> <a
                href="{% url 'home:profile_page' species.user.pk %}">{{species.user.username }}</a></p>
            <p class="subtitle is-6"><strong>Parity Mode: </strong>{{ species.parity_mode.parity_mode_desc }}</p>
            <p class="subtitle is-6"><strong>Conservation Status: </strong> {{ species.iucn.iucn_status }} </p>
            <p class="subtitle is-6"><strong>Activity: </strong> {% for activities in species.activity_set.all %}
              {{ activities.activity_kind }},
              {% endfor %}</p>

            <p class="subtitle is-6"><strong>Habitat: </strong>{% for micro_habitats in species.micro_habitat_set.all %}
              {{ micro_habitats.micro_habitat_name }},
              {% endfor %}</p>


          </div>

          {% if user.is_authenticated and user.is_staff %}
          <footer class="card-footer has-background-warning">

            <a href="{% url 'home:approve_species' species.pk %}" class='card-footer-item'>
              (Approve Species)
            </a>
            <a href="{% url 'home:edit_species' species.pk %}" class='card-footer-item'>
              (Edit Species)
            </a>
          </footer>
          {% endif %}
          <footer class="card-footer has-background-warning">
            {% if user.is_authenticated and user.is_staff %}
            <a href="{% url 'home:delete_species' species.pk %}" class='card-footer-item'>
              (Delete Species)
            </a>
            <a href="{% url 'home:species_pdf_creator' species.pk %}" class='card-footer-item'>
              (Generate PDF)
            </a>
            {% endif %}
            <a href="{% url 'home:species_detail' species.pk %}" class='card-footer-item'>(More info)</a>
          </footer>
        </div>
      </div>

      {% endfor %}


    </div>


  </div>
  </div>
</section>

{% endblock %}

home/templates/home/account/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block title %} My Page {% endblock %}
{% block content %}

<article class="panel is-success">
  <p class="panel-heading">
  </p>
</article>


<nav class="breadcrumb is-centered" aria-label="breadcrumbs">
  <ul>
    <li><a href="{% url 'home:index' %}"><span class="icon is-small">
    <i class="fa-solid fa-frog"></i>
    </span>
    <span><strong>Amphibians Worldwide</strong></span>
    <span class="icon is-small">
    <i class="fa-solid fa-earth-europe"></i>
    </span></a></li>

    <li><a href="javascript:history.back()" aria-current="page"><span class="icon is-small">
      <i class="fa-solid fa-magnifying-glass"></i>
    </span>
    <span><strong>Filtered By</strong>
    </span></a></li>

    <li class="is-active"><a href="#" aria-current="page"><span class="icon is-small">
      <i class="fa-solid fa-user"></i>
    </span>
    <span><strong>{{user.username}}'s Page</strong>
    </span>
  </a></li>
    
  </ul>
</nav>

<section class="section">
  <div class="container">
    <div class="column is-one-third is-offset-one-third is-centered">
      <div class="box">
        <div class="image image-user">
          <figure class="is-flex is-align-items-center is-justify-content-center image is-3by2">
            {% if user.user_profile.profile_image %}
            <img src="{{ user.user_profile.profile_image.url }}" alt="Image">
            {% else %}
            <img src="{% static 'home/images/user_profile.jpg' %}" alt="Image">
            {% endif %}
          </figure>
        </div>

        <div class="content">
          <nav class="level is-mobile">
            <div class="level-left">
              <p class="level-item">
                <strong>{{ user.user_profile.educational_institution }}</strong>
              </p>

            </div>
          </nav>

          {% if user.user_profile.academia_publication %}
          <p class="subtitle is-6"><strong>academia.edu: </strong></p>
          <a href="{{ user.user_profile.academia_publication }}"> academia.edu</a>
          {% endif %}
          {% if user.user_profile.publication_1 %}
          <p class="subtitle is-6"><strong>Publications: </strong></p>
          <a href="{{ user.user_profile.publication_1 }}"> Publication 1</a>
          {% endif %}
          {% if user.user_profile.publication_2 %}
          <a href="{{ user.user_profile.publication_2 }}"> Publication 2</a>
          {% endif %}
          {% if user.user_profile.publication_3 %}
          <a href="{{ user.user_profile.publication_3 }}"> Publication 3</a>
          {% endif %}
          {% if user.user_profile.publication_4 %}
          <a href="{{ user.user_profile.publication_4 }}"> Publication 4</a>
          {% endif %}
          {% if user.user_profile.publication_5 %}
          <a href="{{ user.user_profile.publication_5 }}"> Publication 5</a>
          {% endif %}
          <br>

          <strong>Bio:</strong>
          <br>
          <p>{{ user.user_profile.bio}} </p>
        </div>
        
        <nav class="level is-mobile">
          <div class="level-left">
            <a class="level-item">
              <span class="icon is-large">
                <a href="{{ user.user_profile.linked_in }}"> <i class="fa-brands fa-linkedin"></i> </a>
              </span>
            </a>
            <a class="level-item">
              <span class="icon is-large">
                <a href="mailto:{{user.email}}"> <i class="fa-solid fa-envelope"></i> </a>
              </span>
            </a>
            <a class="level-item">
              <span class="icon is-large">
                <a href="{{ user.user_profile.university_profile }}"> <i class="fa-solid fa-building-columns"></i> </a>
              </span>
            </a>
          </div>
        </nav>
      </div>

    </div>
  </div>
</section>


{% endblock %}

home/templates/home/account/submit_species.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Submit Species {% endblock %}
{% block content %}

<article class="panel is-success">
  <p class="panel-heading">
  </p>
</article>

<nav class="breadcrumb is-centered" aria-label="breadcrumbs">
  <ul>
    <li><a href="{% url 'home:index' %}"><span class="icon is-small">
          <i class="fa-solid fa-frog"></i>
        </span>
        <span><strong>Amphibians Worldwide</strong></span>
        <span class="icon is-small">
          <i class="fa-solid fa-earth-europe"></i>
        </span></a></li>

    <li><a href="javascript:history.back()" aria-current="page"><span class="icon is-small">
          <i class="fa-solid fa-magnifying-glass"></i>
        </span>
        <span><strong>Filtered By</strong>
        </span></a></li>

    <li class="is-active"><a href="#" aria-current="page"><span class="icon is-small">
          <i class="fa-solid fa-frog"></i>
        </span>
        <span><strong>Submit Species</strong>
        </span>
        <span class="icon is-small">
          <i class="fa-solid fa-book"></i>
        </span>
      </a></li>

  </ul>
</nav>



<section class="section">
  <div class="container">

    <section class="section">
      {% if messages %}
      {% for message in messages %}
      <article class="message is-danger">
        <div class="message-header">
          <p>Woops!</p>
        </div>
        <div class="message-body">
          {{ message }}
        </div>
      </article>
      {% endfor %}
      {% endif %}

      <form action="{% url 'home:submit_species' %}" method=POST enctype="multipart/form-data"> {% csrf_token %}
        <!-- {{ order_form.as_p }}
            {{ family_form.as_p }} -->
        {{ species_form.as_p }}
        <!-- {{ micro_habitat_form.as_p }}
            {{ activity_form.as_p }}
            {{ nesting_site_form.as_p }}
            {{ continent_form.as_p }}
            {{ country_form.as_p }} -->



        <div class="field is-grouped">
          <div class="control">
            <button class="button is-info has-text-success">Submit</button>
          </div>

        </div>
      </form>
      
  </div>
</section>


{% endblock %}

home/templates/home/account/update_account.html
{% extends 'base.html' %}
{% block title %} Update Account {% endblock %}
{% block content %}

{% if request.user.is_authenticated %}
<article class="panel is-success">
  <p class="panel-heading">
  </p>
</article>

<nav class="breadcrumb is-centered" aria-label="breadcrumbs">
  <ul>
    <li><a href="{% url 'home:index' %}"><span class="icon is-small">
          <i class="fa-solid fa-frog"></i>
        </span>
        <span><strong>Amphibians Worldwide</strong></span>
        <span class="icon is-small">
          <i class="fa-solid fa-earth-europe"></i>
        </span></a></li>

    <li><a href="javascript:history.back()" aria-current="page"><span class="icon is-small">
          <i class="fa-solid fa-magnifying-glass"></i>
        </span>
        <span><strong>Filtered By</strong>
        </span></a></li>

    <li class="is-active"><a href="#" aria-current="page"><span class="icon is-small">
          <i class="fa-solid fa-user"></i>
        </span>
        <span><strong>{{user.username}}</strong>
        </span>
      </a></li>

  </ul>
</nav>

{% if form.errors %}
<article class="message is-danger">
  <div class="message-header">
    <p>Woops!</p>
  </div>
  <div class="message-body">
    Input invalid! Please try again!
  </div>
</article>

{% else %}
{% for message in messages %}
<article class="message is-info">
  <div class="message-header">
    <p>Success!</p>
  </div>
  <div class="message-body">
    {{ message }}
  </div>
</article>
{% endfor %}
{% endif %}

<form action="{% url 'home:update_account' %}" method=POST enctype="multipart/form-data"> {% csrf_token %}
  <div class="field">
    {{ u_form.as_p }}
    {{ p_form.as_p}}
  </div>
  <button class="button is-info has-text-success">Update</button>
</form>



</div>
</section>
{% endif %}
{% endblock %}